name: RipSecrets
on: [pull_request]
jobs:
  ripsecrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download ripsecrets
        run: |
          brew list

