name: RipSecrets
on: [pull_request]
jobs:
  ripsecrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download ripsecrets
        run: |
          get https://github.com/sirwart/ripsecrets/releases/download/v0.1.5/ripsecrets-0.1.5-x86_64-unknown-linux-gnu.tar.gz
          tar -xzf ripsecrets-0.1.5-x86_64-unknown-linux-gnu.tar.gz
          cd ripsecrets-0.1.5-x86_64-unknown-linux-gnu
          chmod +x ripsecrets
          sudo mv ripsecrets /usr/local/bin

      - name: Run ripsecrets
        run: |
          ripsecrets
